import { useState } from 'react';
import { getAICommentary } from '../services/api';

// cached / onGenerated props let Company.jsx persist the commentary across tab switches
export default function AICommentary({ company, product, snapshot, asOfDate, currency,
                                       cached = null, onGenerated = null }) {
  const [local, setLocal]         = useState(null);
  const [generatedAt, setGeneratedAt] = useState(null);
  const [loading, setLoading]     = useState(false);

  // Use cached value from parent if available, otherwise fall back to local state
  const commentary = cached ?? local;

  const generate = async () => {
    setLoading(true);
    try {
      const data = await getAICommentary(company, product, snapshot, asOfDate, currency);
      setLocal(data.commentary);
      setGeneratedAt(data.generated_at);
      onGenerated?.(data.commentary);   // bubble up to parent cache
    } catch {
      const err = 'Failed to generate commentary. Please check your API key.';
      setLocal(err);
      onGenerated?.(err);
    }
    setLoading(false);
  };

  return (
    <div className="rounded-xl overflow-hidden"
         style={{ backgroundColor: '#111D3E', border: '1px solid #1B2B5A' }}>
      <div className="p-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-sm font-semibold text-white">AI Portfolio Commentary</h3>
            <p className="text-xs mt-1" style={{ color: '#64748B' }}>
              Investment committee-ready analysis generated by Claude
            </p>
          </div>
          <button onClick={generate} disabled={loading}
            className="text-xs px-4 py-2 rounded-lg font-medium transition-all"
            style={{ backgroundColor: loading ? '#1B2B5A' : '#3B82F6',
                     color: 'white', opacity: loading ? 0.7 : 1 }}>
            {loading
              ? <span className="flex items-center gap-2">
                  <span className="w-3 h-3 border border-white border-t-transparent rounded-full animate-spin" />
                  Analyzing...
                </span>
              : commentary ? 'Regenerate' : 'Generate Analysis'}
          </button>
        </div>

        {!commentary && !loading && (
          <div className="text-center py-8 rounded-lg"
               style={{ backgroundColor: '#0A0F1E', border: '1px dashed #1B2B5A' }}>
            <div className="text-2xl mb-2">🤖</div>
            <div className="text-sm" style={{ color: '#64748B' }}>
              Click "Generate Analysis" for AI-powered portfolio commentary
            </div>
          </div>
        )}

        {commentary && (
          <div className="space-y-3">
            {generatedAt && (
              <div className="text-xs" style={{ color: '#334155' }}>
                Generated: {new Date(generatedAt).toLocaleString()} · As of: {asOfDate}
              </div>
            )}
            <div className="prose prose-sm max-w-none">
              {commentary.split('\n').map((line, i) => {
                if (!line.trim()) return <div key={i} className="h-2" />;
                if (line.match(/^\d+\.|^[A-Z\s]{5,}$/))
                  return <div key={i} className="font-semibold text-sm mt-3 mb-1"
                              style={{ color: '#93C5FD' }}>{line}</div>;
                if (line.startsWith('•') || line.startsWith('-'))
                  return <div key={i} className="flex gap-2 text-sm" style={{ color: '#CBD5E1' }}>
                    <span style={{ color: '#3B82F6' }}>•</span>
                    <span>{line.replace(/^[•\-]\s*/, '')}</span>
                  </div>;
                return <p key={i} className="text-sm" style={{ color: '#CBD5E1' }}>{line}</p>;
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}